// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoqRtrzVQSV5hONdkHqG-t2qk8K8k6ZEE',
    appId: '1:693261998763:web:fc47d7be85043a01a335ee',
    messagingSenderId: '693261998763',
    projectId: 'flutter-notification-922d1',
    authDomain: 'flutter-notification-922d1.firebaseapp.com',
    storageBucket: 'flutter-notification-922d1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNzFY0-RiUz4N_Fr5oiq9Ws7BCsN23BmI',
    appId: '1:693261998763:android:2fe30770c263e54ba335ee',
    messagingSenderId: '693261998763',
    projectId: 'flutter-notification-922d1',
    storageBucket: 'flutter-notification-922d1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9B2VI0xq3NrKe2VyFcIdbmYUTwniEQDU',
    appId: '1:693261998763:ios:dda444ff664aa849a335ee',
    messagingSenderId: '693261998763',
    projectId: 'flutter-notification-922d1',
    storageBucket: 'flutter-notification-922d1.appspot.com',
    iosClientId: '693261998763-ib6rnj3fqss4h5l0r9i9d2u5dna215v3.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9B2VI0xq3NrKe2VyFcIdbmYUTwniEQDU',
    appId: '1:693261998763:ios:15dd1ac497ad1176a335ee',
    messagingSenderId: '693261998763',
    projectId: 'flutter-notification-922d1',
    storageBucket: 'flutter-notification-922d1.appspot.com',
    iosClientId: '693261998763-hggrrlamnef08ob0ebcrtvceqvg49pj0.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterNotification.RunnerTests',
  );
}
